apiVersion: v1
kind: Service
metadata:
   name: backend-svc
spec:
  selector:
    server: backend
    ports:
       - port: 8080
         targetPort: 8080
         protocol: tcp
         nodePort: 31100
    type: NodePort     
