apiVersion: apps/v1
kind: Deployment
metadata:
   name: backend
   labels:
     server: backend
spec:
     replicas: 1
     selector:
       matchLabels:
         server: backend
     template:
       metadata:
         labels:
            server: backend     
       spec:
          containers:
            - name: backend-cont
              image: master101/wanderlust-project_backend:latest
              ports:
                - containerPort: 8080    
