apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend
    labels:
      server: frontend
spec:
    replicas: 1
    selector:
      matchLabels: 
        server: frontend

    template:
      metadata:
         labels:
           server: frontend
      spec:
        containers:
          - name: frontend-cont
            image: master101/wanderlust-project_frontend:latest
            ports:
              - containerPort: 5173
                   
