apiVersion: v1
kind: Deployment
metadata:
    name: fontend
    labels:
      server: frontend
spec:
    replica: 1
    selector:
      matchLables: 
        server: frontend

    template:
      metadata:
        name: frontend
      spec:
        containers:
            name: frontend-cont
            image: master101/wanderlust-project_frontend:latest
            ports:
              - containerPort: 5173
                   
