apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pvc
spec: 
    accessModes:
        - ReadWriteOnce
    storageClassName: pvc
    resources:
       requests:
         storage: 5Gi      
