apiVersion: v1
kind: Deployment
metadata:
    name: redis-deployment
    labels:
       matchLabels:
          app: redis
spec:
     metadata:
       name: redis
       selectors:
          matchLabels:
             app: redis
       template:
          metadata:
              name: redis
          spec: 
              containers:
                 name: redis-cont
                 image: redis:latest
                 ports: 
                   - containerPort: 6379
                 volumeMounts:
                   - name: redisVolume
                     mountPath: /data
              volumes:
                 - name: redisVolume
                   persistentVolumeClaim:
                     claimName: pvc
       
